### PR TITLE
Refactored python library

### PR DESCRIPTION
**Pull request by tclose**
This PR consists of a fairly substantial refactoring of the lib9ml python library. In the end, I did not add any of the new features I have planned, so it should be okay to merge with the version 1.0 branch (which should make sharing bug fixes between the master and version 1 branches *considerably* more straightforward).

* The names of all classes match what they are called in the specification, and their module name matches the specification section
* All existing utilities and validators (for `Dynamics` components), including XML readers and writers, have been split into a base and derived classes, where the base class contains methods for manipulating elements that will be common across all component-class types (i.e. `Dynamics`, `ConnectionRule` and Distribution`)

### CODE REVIEW

**Comment by tclose** [comment]
Forgot to say that I copied all the relevant validators and utils from Dynamics (those derived from the common base class) to the Distribution and ConnectionRule packages and cleaned out the Dynamics specific actions so they are ready to implement ConnectionRule and Distribution-specific validators

**Comment by apdavison** [comment]
Hi Tom,

This PR is too huge for me to review properly. Before merging, could I just ask you to check that the code for the Brunel model runs and gives sensible results: https://bitbucket.org/apdavison/brunel2000_nineml

Cheers,

Andrew

**Comment by tclose** [comment]
Which version of PyNN does it expect. Is the latest master branch fine or
do I need to checkout the latest alpha?

Cheers,

Tom

On 3 February 2015 at 21:22, Andrew Davison <notifications@github.com>
wrote:

>  Hi Tom,
>
> This PR is too huge for me to review properly. Before merging, could I
> just ask you to check that the code for the Brunel model runs and gives
> sensible results: https://bitbucket.org/apdavison/brunel2000_nineml
>
> Cheers,
>
> Andrew
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/INCF/nineml/pull/78#issuecomment-72641643>.
>



-- 
Thomas G. Close, PhD.
Postdoctoral Researcher,
Computational Neuroscience Unit,
Okinawa Institute of Science and Technology
e: tclose@oist.jp
w: +81 98 966 8804

**Comment by apdavison** [comment]
Sorry, I forgot to say. It needs the apdavison/nineml branch (which I will merge into master once the nineml and nineml2nmodl packages have been released).

**Comment by tclose** [comment]
Hi Andrew,

I have got the brunel model running but haven't checked its output (I am
assuming that it won't change).  You will need to pull some minor updates
to the PyNN/nineml branch and the Brunel model first though.

Cheers,

Tom

On 3 February 2015 at 22:55, Andrew Davison <notifications@github.com>
wrote:

>  Sorry, I forgot to say. It needs the apdavison/nineml branch (which I
> will merge into master once the nineml and nineml2nmodl packages have been
> released).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/INCF/nineml/pull/78#issuecomment-72653575>.
>



-- 
Thomas G. Close, PhD.
Postdoctoral Researcher,
Computational Neuroscience Unit,
Okinawa Institute of Science and Technology
e: tclose@oist.jp
w: +81 98 966 8804

**Comment by apdavison** [comment]
I strongly dislike the name change from `X` to `XComponent`, e.g. `ConnectionRule` to `ConnectionRuleComponent`and `RandomDistribution` to `RandomDistributionComponent`.

One of the original design goals for the Python nineml library was to have a user-friendly API. Therefore having longer names is in general undesirable, and having the names of all classes match exactly what they are called in the specification is unnecessary, as long as the correspondence and meaning are clear.

**Comment by tclose** [comment]
My motivation behind those changes was to keep a one-to-one mapping between the specs and the python library and in that case `ConnectionRule`, `Dynamics` and `RandomDistribution` are the names of the blocks that sit under the component class. However, I would be happy to treat them as a special case and call them `ConnectionRuleBlock`, `DynamicsBlock`, etc in the python library as it is a bit weird having a `Dynamics` object sitting within a `DynamicsClass` object.

**Comment by tclose** [comment]
I have created a new unit test called `user_layer.test_network.py`, which is based on the `run_brunel_test.py` file in the brunel model. So I think it should be good to merge now if you are okay with design decisions I have made.

**Comment by tclose** [comment]
I meant to mention that the one thing I have included that is looking forward to v2.0 is that `<RandomDistribution>` elements map onto `Distribution` python objects. However, I have added an alias for both the class and component (e.g. `Distribution`->`RandomDistribution`, etc) when importing them into the AL and UL namespaces. Does this sound okay?

**Pull request merged**
