### PR TITLE
added a link to the specification pdf on the front page

### PR DESCRIPTION
**Pull request by iraikov**

### CODE REVIEW

**Comment by apdavison** [comment]
What is the reasoning behind having the LaTeX sources for the spec in the gh-pages branch? Are you envisaging automated building of the PDF?

**Comment by apdavison** [comment]
Would the intention then be to remove the spec from the master branch?

**Comment by tclose** [comment]
I don't think moving the spec from the master branch would be a good idea.
I suspect that Ivan is envisaging automated building but we could probably
do that from the master branch couldn't we?

On 14 January 2015 at 17:36, Andrew Davison <notifications@github.com>
wrote:

>  Would the intention then be to remove the spec from the master branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/INCF/nineml/pull/67#issuecomment-69884586>.
>



-- 
Thomas G. Close, PhD.
Postdoctoral Researcher,
Computational Neuroscience Unit,
Okinawa Institute of Science and Technology
e: tclose@oist.jp
w: +81 98 966 8804

**Comment by apdavison** [comment]
Yes, we could build from the master branch.

**Comment by iraikov** [comment]
What is the way to build from the master branch?

**Comment by iraikov** [comment]
Yes, I don't care so much where the LaTeX source lives, as long as there is a way to have a PDF file on the NineML home page. Or if you all prefer, have a PDF for the stable (released) spec, and a PDF for the spec in progress.

**Comment by tclose** [comment]
Closing this in favour of Andrew's solution

**Pull request closed without merging**
