### PR TITLE
Version 1.0 final

### PR DESCRIPTION
**Pull request by tclose**
This pull request makes the final round of changes for version 1.0 that were discussed in the last Google Hangout and is to serve as a formal vote by the 9ML standardisation committee members.

### CODE REVIEW

**Comment by mondus** [comment]
:+1:

**Comment by ajc158** [comment]
:+1:

**Comment by erikdsj** [comment]
:+1:

**Comment by apdavison** [comment]
+1

**Comment by ajc158** [comment]
+1

**Comment by mondus** [comment]
+1

**Comment by jougs** [comment]
+1

**Comment by mondus** [comment]
+1

**Comment by NineML-Committee** [comment]
The committee approves the changes above unanimously

**Pull request merged**
