### PR TITLE
Piecewise functions

### PR DESCRIPTION
**Pull request by tclose**
This PR addresses issue #74.

In the MathML subset used by SBML you are able to define piecewise functions, which could (probably will) be the long term plan to support this feature. However, in the mean time this PR adds similar functionality to NineML MathInline syntax, copying most of the format from MathML.

### CODE REVIEW

**Comment by apdavison** [comment]
Again, I don't think I can really review this until the refactoring PR is merged.

**Comment by tclose** [comment]
No worries, I am testing out the Brunel model now so hopefully I can get
back to you soon.

On 3 February 2015 at 21:32, Andrew Davison <notifications@github.com>
wrote:

>  Again, I don't think I can really review this until the refactoring PR
> is merged.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/INCF/nineml/pull/83#issuecomment-72642831>.
>



-- 
Thomas G. Close, PhD.
Postdoctoral Researcher,
Computational Neuroscience Unit,
Okinawa Institute of Science and Technology
e: tclose@oist.jp
w: +81 98 966 8804

**Comment by tclose** [comment]
I meant to say that I could rebase them on to the old master if there is a
problem with the refactoring but if there is not a problem it would be
easier to wait until it is merged

On 3 February 2015 at 21:34, Tom Close <tclose@oist.jp> wrote:

> No worries, I am testing out the Brunel model now so hopefully I can get
> back to you soon.
>
> On 3 February 2015 at 21:32, Andrew Davison <notifications@github.com>
> wrote:
>
>>  Again, I don't think I can really review this until the refactoring PR
>> is merged.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/INCF/nineml/pull/83#issuecomment-72642831>.
>>
>
>
>
> --
> Thomas G. Close, PhD.
> Postdoctoral Researcher,
> Computational Neuroscience Unit,
> Okinawa Institute of Science and Technology
> e: tclose@oist.jp
> w: +81 98 966 8804
>



-- 
Thomas G. Close, PhD.
Postdoctoral Researcher,
Computational Neuroscience Unit,
Okinawa Institute of Science and Technology
e: tclose@oist.jp
w: +81 98 966 8804

**Comment by tclose** [comment]
Will reopen this in the new lib9ML repository

**Pull request closed without merging**
