### PR TITLE
Random variable

### PR DESCRIPTION
**Pull request by tclose**
This PR is designed to be pulled into master after a "version1" has been branched off it and addresses #31 by adding a `RandomVariable` element, which is drawn from a random distribution that is defined via UncertML (www.uncertml.org). These `RandomVariable` elements are expected to be valid inside transitions (i.e. not regimes) and connection rules, as well as the `Distribution` component classes I have proposed. The `Distribution` component classes can then be used to define random distributions over a container.

### CODE REVIEW

**Comment by tclose** [comment]
This failing because an uncertml xml schema isn't getting copied to travis. How do I add it to list?

**Comment by apdavison** [comment]
Maybe edit the field "package_data" in setup.py?

**Comment by tclose** [comment]
That seems to have worked but I am now getting errors with the schema
parser... Will look into this later.

Cheers,

Tom

On 3 February 2015 at 21:32, Andrew Davison <notifications@github.com>
wrote:

>  Maybe edit the field "package_data" in setup.py?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/INCF/nineml/pull/82#issuecomment-72642745>.
>



-- 
Thomas G. Close, PhD.
Postdoctoral Researcher,
Computational Neuroscience Unit,
Okinawa Institute of Science and Technology
e: tclose@oist.jp
w: +81 98 966 8804

**Comment by tclose** [comment]
Could this possibly be due to a bug in `lxml2` described here, https://bugzilla.gnome.org/show_bug.cgi?id=630130? It  runs fine on my local installation.

How do we check which version of lxml Travis is installing, I assume it is the latest one from PyPi (I am using lxml v3.4).

**Comment by tclose** [comment]
I will have reopen this in the new lib9ML repository

**Pull request closed without merging**
