### PR TITLE
Add Constants to python library

### PR DESCRIPTION
**Pull request by tclose**
This PR adds support for physical constants to the python library (see #15). 

It would seem necessary to add some way to specify constants such as Faraday's, Ideal Gas Constant in ComponentClasses to prevent users having to set their values via parameters. The only problem I can see with it is that it opens up the possibility for abuse, where actual parameters get defined as "constants" out of laziness.

Note: Constant tag is currently in the specification, but can be taken out before version 1.0 is finalised if there are objections.

### CODE REVIEW

**Comment by apdavison** [comment]
Does it really take 141 commits to add constants? I guess this PR also includes stuff that is in the "refactoring" PR. Perhaps this could be rebased or something after the other PRs are merged, so we can see precisely what has changed in adding constants?

**Comment by tclose** [comment]
Yeah, it is the way that GitHub works. As soon as the refactoring PR is
merged (assuming all is okay), only the differences between the contstants
branch and the new master head will be shown in the PR.

On 3 February 2015 at 21:28, Andrew Davison <notifications@github.com>
wrote:

>  Does it really take 141 commits to add constants? I guess this PR also
> includes stuff that is in the "refactoring" PR. Perhaps this could be
> rebased or something after the other PRs are merged, so we can see
> precisely what has changed in adding constants?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/INCF/nineml/pull/81#issuecomment-72642371>.
>



-- 
Thomas G. Close, PhD.
Postdoctoral Researcher,
Computational Neuroscience Unit,
Okinawa Institute of Science and Technology
e: tclose@oist.jp
w: +81 98 966 8804

**Comment by tclose** [comment]
I have reopened this in the new lib9ML repository

**Comment by tclose** [comment]
New PR https://github.com/INCF/lib9ML/pull/1

**Pull request closed without merging**
